// Defining action types as constants for product listing, product details, and error handling
const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
const PRODUCTS_FAIL = "PRODUCTS_FAIL";
const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
const CLEAR_ERRORS = "CLEAR_ERRORS";

// Exporting the action types for use in other parts of the application
export {
  PRODUCTS_REQUEST,
  PRODUCTS_SUCCESS,
  PRODUCTS_FAIL,
  PRODUCT_DETAILS_REQUEST,
  PRODUCT_DETAILS_SUCCESS,
  PRODUCT_DETAILS_FAIL,
  CLEAR_ERRORS,
};
